apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: synapse
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres"
