apiVersion: v1
kind: PersistentVolume
metadata:
  name: synapse-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/synapse
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-pvc
  namespace: synapse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
