apiVersion: v1
kind: Service
metadata:
  name: synapse
  namespace: synapse
spec:
  selector:
    app: synapse
  ports:
    - protocol: TCP
      port: 8008
      targetPort: 8008
      nodePort: 30008 # Expose on a specific NodePort for access
  type: NodePort
