apiVersion: v1
kind: Service
metadata:
  name: synapse
  namespace: synapse
spec:
  type: NodePort
  ports:
    - name: http
      port: 8008
      targetPort: 8008
      nodePort: 30008
    - name: federation
      port: 8448
      targetPort: 8448
      nodePort: 30448
  selector:
    app: synapse
